const {chromium}=require('playwright-core'),assert=require('node:assert/strict'),fs=require('node:fs');
(async()=>{const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||chromium.executablePath(),headless:true,args:['--enable-webgl','--ignore-gpu-blocklist','--use-angle=d3d11']});try{const page=await browser.newPage({viewport:{width:2560,height:1440}}),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error'&&/THREE.WebGLProgram|VALIDATE_STATUS|Shader Error/.test(m.text()))errors.push(m.text());});await page.route('**/src/city-home.mjs',async route=>{const response=await route.fetch();const body=(await response.text()).replace('try{const catalog=',`window.cityVisualCheck=()=>({reflection:current.reflection?.texture.uuid,humans:[...objects.values()].filter(g=>['pedestrian','bicycle','motorcycle','tricycle'].includes(g.userData.track.type)).every(g=>['rocketbox-male-adult-01','rocketbox-male-adult-02'].includes(g.userData.humanAsset)),refined:[...objects.values()].filter(g=>['car','bus','truck'].includes(g.userData.track.type)).every(g=>g.userData.detailProfile==='city-refined')});try{const catalog=`);await route.fulfill({response,body});});const reflections=new Set();await page.goto('http://127.0.0.1:4173/?start=120000');await page.waitForSelector('#loading[hidden]',{state:'attached',timeout:60000});
for(const city of ['tianjin','changchun','chongqing','xian']){await page.locator(`button[data-city="${city}"]`).click();await page.waitForFunction(c=>document.querySelector('#scene').dataset.city===c,city);await page.waitForSelector('#loading[hidden]',{state:'attached'});await page.waitForTimeout(2000);const visual=await page.evaluate(()=>window.cityVisualCheck());assert.ok(visual.reflection);assert.ok(visual.refined);assert.ok(visual.humans);assert.ok(!reflections.has(visual.reflection));reflections.add(visual.reflection);assert.equal(await page.locator('input[type="range"]').count(),0);assert.equal(await page.locator('[data-view] img[src^="data:image/jpeg"]').count(),5);assert.equal(/[A-Za-z]/.test(await page.locator('body').innerText()),false);await page.screenshot({path:`artifacts/city-${city}.png`});console.log(city,await page.locator('#scene').getAttribute('data-active'));}
await page.locator('button[data-city="tianjin"]').click();await page.waitForFunction(()=>document.querySelector('#scene').dataset.city==='tianjin');await page.locator('#play').click();const t=Number(await page.locator('#scene').getAttribute('data-time'));const flow=await import('../src/city-flow.mjs');const config=JSON.parse(fs.readFileSync('data/sind/cities/tianjin.json'));assert.equal(Number(await page.locator('#flow-recent').innerText()),flow.flowAt(config,t).recent);
for(const view of ['junction','street','sample']){await page.locator(`[data-view="${view}"]`).click();await page.waitForTimeout(1100);await page.screenshot({path:`artifacts/city-${view}.png`});}
await page.goto('http://127.0.0.1:4173/?start=1201590');await page.waitForSelector('#loading[hidden]',{state:'attached',timeout:60000});await page.waitForFunction(()=>Number(document.querySelector('#scene').dataset.time)<10000,null,{timeout:20000});const loopAt=Number(await page.locator('#scene').getAttribute('data-time'));assert.equal(Number(await page.locator('#flow-total').innerText().then(t=>t.match(/\d+/)[0])),flow.flowAt(config,loopAt).total);
// Freeze the recorded timestamp before rendering; GPU warm-up must not skip the yellow interval.
await page.route('**/src/city-home.mjs',async route=>{const response=await route.fetch();const body=(await response.text()).replace('try{const catalog=','playing=false;try{const catalog=');await route.fulfill({response,body});});
const yellow=config.signals.find(e=>e.slice(1).includes(3));await page.goto('http://127.0.0.1:4173/?start='+yellow[0]);await page.waitForSelector('#loading[hidden]',{state:'attached',timeout:60000});assert.ok(await page.locator('.signal[data-state="3"]').count());await page.goto('http://127.0.0.1:4173/analysis.html');await page.waitForSelector('#loading[hidden]',{state:'attached',timeout:60000});assert.ok(await page.locator('#analysis').count());assert.equal(errors.length,0,errors.join('\n'));console.log('Four cities, five thumbnails, Chinese UI, flow, loop reset and analysis route passed.');}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
